### ISSUE TITLE
error dup key

### ISSUE THREAD

**Issue by oziee** [NicolasRitouet/dpd-fileupload-demo#2] opened 2015-02-15 00:07 UTC
hi
using this demo code and dpd-fileupload.. when i select many files things start to go wrong
doing only one file at a time doesnt seem to throw any errors

selected 16 files and received 4 errors like this

context {"name":"MongoError","index":0,"code":11000,"errmsg":"insertDocument :: caused by :: 11000 E11000 duplicate key error index: -deployd.fileuploadfileupload.$_id_  dup key: { : ObjectId('54dfe1f77b9ace04031efdb9') }"} +4s

obviously there must already be a record with that id..

**Comment by NicolasRitouet** [comment] 2015-02-15 14:08
Hi @oziee 
I'll try to reproduce that and I let you know.

**Comment by NicolasRitouet** [comment] 2015-05-03 06:27
hi @oziee 
Since there's been a few updates since you reported your issue, is your problem still here?
Have you tried to update with the latest version of deployd and dpd-fileupload?

If not, I'll try to dig into this.

**Comment by oziee** [comment] 2015-05-03 06:34
Hi.. i think i just deleted my whole dpd install and started again from scratch.. I havnt seen the same error since

**Comment by NicolasRitouet** [comment] 2015-05-03 06:45
I quickly tried to upload more than 10 files at the same time, and it didn't work for some of them.

I'll close this ticket and move this issue to the dpd-fileupload repo:
https://github.com/NicolasRitouet/dpd-fileupload/issues/21

**Closed by NicolasRitouet** 2015-05-03 06:45 UTC
